server:
  port: 82
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mrrshu/springclouddemoconfig.git

          username:
          password: