server:
  port: 9001
spring:
  application:
    name: mysqlclient
  datasource:
    driverClassName: com.mysql.jdbc.Driver  #driver-class-name
    url: jdbc:mysql://localhost:3306/suxiaowei_test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true